//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the "CommandsGenerator.fsx" script.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBoard.Commands

open System
open System.Runtime.Serialization

[<DataContract>]
type CreateUser = 
    {
        [<field: DataMember(Name = "UserId@")>]
        UserId: Guid

        [<field: DataMember(Name = "Login@")>]
        Login: String

        [<field: DataMember(Name = "Password@")>]
        Password: String

        [<field: DataMember(Name = "Name@")>]
        Name: String
    }
    interface ICommand

[<DataContract>]
type SetUserPhoto = 
    {
        [<field: DataMember(Name = "UserId@")>]
        UserId: Guid

        [<field: DataMember(Name = "Photo@")>]
        Photo: Byte[]

        [<field: DataMember(Name = "OriginalVersion@")>]
        OriginalVersion: Int32
    }
    interface ICommand

[<DataContract>]
type CreateProject = 
    {
        [<field: DataMember(Name = "ProjectId@")>]
        ProjectId: Guid

        [<field: DataMember(Name = "CreatorId@")>]
        CreatorId: Guid

        [<field: DataMember(Name = "Caption@")>]
        Caption: String
    }
    interface ICommand

[<DataContract>]
type CreateTaskStatus = 
    {
        [<field: DataMember(Name = "ProjectId@")>]
        ProjectId: Guid

        [<field: DataMember(Name = "TaskStatusCaption@")>]
        TaskStatusCaption: String

        [<field: DataMember(Name = "OriginalVersion@")>]
        OriginalVersion: Int32
    }
    interface ICommand

[<DataContract>]
type CreateUserStoryStatus = 
    {
        [<field: DataMember(Name = "ProjectId@")>]
        ProjectId: Guid

        [<field: DataMember(Name = "UserStoryStatusCaption@")>]
        UserStoryStatusCaption: String

        [<field: DataMember(Name = "OriginalVersion@")>]
        OriginalVersion: Int32
    }
    interface ICommand

[<DataContract>]
type AddTaskStatusToUserStoryStatus = 
    {
        [<field: DataMember(Name = "ProjectId@")>]
        ProjectId: Guid

        [<field: DataMember(Name = "UserStoryPosition@")>]
        UserStoryPosition: Int32

        [<field: DataMember(Name = "TaskStatusPosition@")>]
        TaskStatusPosition: Int32

        [<field: DataMember(Name = "OriginalVersion@")>]
        OriginalVersion: Int32
    }
    interface ICommand
